security:
    # Hash des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: plaintext

    # Fournisseur utilisateurs
    providers:
        users_in_memory:
            memory:
                users:
                    tradmin:
                        password: 'H0166GTZ25'
                        roles: [ROLE_ADMIN]

                    ravimin:
                        password: '78eede1Best1'
                        roles: [ROLE_USER]

    # Firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users_in_memory

            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: /admin

            logout:
                path: app_logout
                target: app_login

    # Contrôle accès
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: plaintext