vich_uploader:
    db_driver: orm

    mappings:
        article_images:
            uri_prefix: /uploads/articles
            upload_destination: '%kernel.project_dir%/public/uploads/articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        administrative_documents:
            uri_prefix: /uploads/documents
            upload_destination: '%kernel.project_dir%/public/uploads/documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        client_documents:
            uri_prefix: /uploads/client-documents
            upload_destination: '%kernel.project_dir%/public/uploads/client-documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer