# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

    app.mailjet.contact_cc_emails:
        - 'kmcom20@yahoo.fr'
        - 'Inanc93700@gmail.com'
        - 'info@traductions-legales.fr'

    app.mailjet.traitement_cc_emails:
        - 'kmcom20@yahoo.fr'
        - 'Inanc93700@gmail.com'
        - 'info@traductions-legales.fr'

    app.mailjet.document_traduit_cc_emails:
        - 'info@traductions-legales.fr'

    env(STRIPE_SECRET_KEY): ''
    env(STRIPE_PUBLIC_KEY): ''
    env(MAILJET_API_KEY): ''
    env(MAILJET_API_SECRET): ''
    env(MAILJET_TEMPLATE_CONFIRMATION_ID): '8108111'
    env(MAILJET_TEMPLATE_CREDENTIALS_ID): '8108287'
    env(MAILJET_TEMPLATE_CONTACT_ID): '8148551'
    env(MAILJET_TEMPLATE_TRAITEMENT_ID): '8148687'
    env(MAILJET_TEMPLATE_DOCUMENT_TRADUIT_ID): '8186658'
    env(MAILJET_SENDER_EMAIL): 'contact@traductions-legales.fr'
    env(MAILJET_TRAITEMENT_EMAIL): 'traitement@traductions-legales.fr'
    env(MAILJET_SUPPORT_EMAIL): 'support@traduction-legale.fr'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\StripeCheckoutService:
        arguments:
            $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'

    App\Service\MailjetService:
        arguments:
            $apiKey: '%env(MAILJET_API_KEY)%'
            $apiSecret: '%env(MAILJET_API_SECRET)%'
            $confirmationTemplateId: '%env(int:MAILJET_TEMPLATE_CONFIRMATION_ID)%'
            $credentialsTemplateId: '%env(int:MAILJET_TEMPLATE_CREDENTIALS_ID)%'
            $contactTemplateId: '%env(int:MAILJET_TEMPLATE_CONTACT_ID)%'
            $processingTemplateId: '%env(int:MAILJET_TEMPLATE_TRAITEMENT_ID)%'
            $translatedDocumentTemplateId: '%env(int:MAILJET_TEMPLATE_DOCUMENT_TRADUIT_ID)%'
            $senderEmail: '%env(MAILJET_SENDER_EMAIL)%'
            $supportEmail: '%env(MAILJET_SUPPORT_EMAIL)%'
            $processingEmail: '%env(MAILJET_TRAITEMENT_EMAIL)%'
            $contactCcEmails: '%app.mailjet.contact_cc_emails%'
            $processingCcEmails: '%app.mailjet.traitement_cc_emails%'
            $translatedDocumentCcEmails: '%app.mailjet.document_traduit_cc_emails%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
